export const SETTINGS = {
  CHUNK_SIZE: 16,
  CHUNK_HEIGHT: 64,
  WORLD_RADIUS: 3,
  BLOCK_SIZE: 1,
  SEA_LEVEL: 20
};

export const PLAYER = {
  HEIGHT: 2,
  EYE_HEIGHT: 1.8,
  RADIUS: 0.3,
  SPEED: 0.1,
  JUMP: 0.15,
  GRAVITY: -0.01
};
