/**
 * @file FeatureLineup.v2.js
 * ///////////////////////////////////////////////////////////////////////////////////////////////////
 * ///////////////////////////////////////////////////////////////////////////////////////////////////
 * ///////////////////////////////////////////////////////////////////////////////////////////////////
 * //////////////////////// DO NOT EDIT THIS FILE ////////////////////////////////////////////////////
 * //////////////////////// DO NOT EDIT THIS FILE ////////////////////////////////////////////////////
 * //////////////////////// DO NOT EDIT THIS FILE ////////////////////////////////////////////////////
 * ///////////////////////////////////////////////////////////////////////////////////////////////////
 * ///////////////////////////////////////////////////////////////////////////////////////////////////
 * ///////////////////////////////////////////////////////////////////////////////////////////////////
 */

window.adLineupVersion = 83;

/**
 * @typedef FeatureLineupArgs
 * @property {string} gameType The gameType of the site showing the feature ad.
 * @property {string} theme The theme of the site showing the feature ad.
 * @property {number} [overrideMonth] Optional. Use to override the month.
 * @property {number} [overrideDay] Optional. Use to override the day.
 */

/**
 * @typedef FeatureLineupGameLink
 * @property gameType {string} The game type id or none.
 * @property theme {string} The theme id or none.
 * @property imageURL {string} The image url filename, relative to the promos directory.
 * @property linkURL {string} Absolute url to the game page, search args excluded.
 * @property [seasonal] {true} Optional. If set to true, the link is considered seasonal and culled if out of season.
 * @property [currentGameCurrentSeason] {true} Optional. If set to true, i indicates if this entry is the location of the current game, current season promo.
 * Example:
 * 	[{
 * 		gameType: "mahjong",
 * 		theme: "247",
 * 		imageURL: "mahjong_247_landscape.jpg",
 * 		linkURL: "https://www.247mahjong.com/"
 * 	}]
 */

/**
 * @typedef FeatureLineupCalendarEntry
 * @property {string} theme The theme id.
 * @property {number} month The month, jan = 1.
 * @property {number} day The day of the month, 1st = 1.
 */

/**
 * 
 * @param {FeatureLineupArgs} args The arguments used to generate the ad lineup.
 */
window.generateFeatureAdLineup = function(args)
{
	/** @type {FeatureLineupGameLink[]} */
	var gameLinks = [
	{
		"gameType": "[none]",
		"theme": "[none]",
		"imageURL": "247games-app-landscape.jpg",
		"linkURL": "https://247games.com/app-games/"
	},
	{
		"gameType": "solitaire",
		"theme": "247",
		"imageURL": "solitaire-247-landscape.jpg",
		"linkURL": "https://www.247solitaire.com/"
	},
	{
		"gameType": "[current]",
		"theme": "[current]",
		"imageURL": "[current]",
		"linkURL": "[current]",
		"currentGameCurrentSeason": true
	},
	{
		"gameType": "solitaire",
		"theme": "247",
		"imageURL": "solitaire-247-landscape.jpg",
		"linkURL": "https://www.247solitaire.com/",
		"seasonal": true
	},
	{
		"gameType": "solitaire",
		"theme": "winter",
		"imageURL": "solitaire-winter-landscape.jpg",
		"linkURL": "http://www.wintersolitaire.com/",
		"seasonal": true
	},
	{
		"gameType": "solitaire",
		"theme": "valentines",
		"imageURL": "solitaire-valentines-landscape.jpg",
		"linkURL": "https://www.valentinesdaysolitaire.com/",
		"seasonal": true
	},
	{
		"gameType": "solitaire",
		"theme": "st-patricks",
		"imageURL": "solitaire-st-patricks-landscape.jpg",
		"linkURL": "https://www.stpatricksdaysolitaire.com/",
		"seasonal": true
	},
	{
		"gameType": "solitaire",
		"theme": "easter",
		"imageURL": "solitaire-easter-landscape.jpg",
		"linkURL": "http://www.solitaireeaster.com/",
		"seasonal": true
	},
	{
		"gameType": "solitaire",
		"theme": "cinco-de-mayo",
		"imageURL": "solitaire-cinco-de-mayo-landscape.jpg",
		"linkURL": "https://www.cincodemayosolitaire.com/",
		"seasonal": true
	},
	{
		"gameType": "solitaire",
		"theme": "spring",
		"imageURL": "solitaire-spring-landscape.jpg",
		"linkURL": "http://www.springsolitaire.com/",
		"seasonal": true
	},
	{
		"gameType": "solitaire",
		"theme": "4th-of-july",
		"imageURL": "solitaire-4th-of-july-landscape.jpg",
		"linkURL": "http://www.4thofjulysolitaire.com/",
		"seasonal": true
	},
	{
		"gameType": "solitaire",
		"theme": "summer",
		"imageURL": "solitaire-summer-landscape.jpg",
		"linkURL": "https://www.solitairesummer.com/",
		"seasonal": true
	},
	{
		"gameType": "solitaire",
		"theme": "fall",
		"imageURL": "solitaire-fall-landscape.jpg",
		"linkURL": "https://www.fallsolitaire.com/",
		"seasonal": true
	},
	{
		"gameType": "solitaire",
		"theme": "halloween",
		"imageURL": "solitaire-halloween-landscape.jpg",
		"linkURL": "http://www.solitairehalloween.com/",
		"seasonal": true
	},
	{
		"gameType": "solitaire",
		"theme": "thanksgiving",
		"imageURL": "solitaire-thanksgiving-landscape.jpg",
		"linkURL": "http://www.thanksgivingsolitaire.com/",
		"seasonal": true
	},
	{
		"gameType": "solitaire",
		"theme": "christmas",
		"imageURL": "solitaire-christmas-landscape.jpg",
		"linkURL": "https://www.christmas-solitaire.com/",
		"seasonal": true
	},
	{
		"gameType": "solitaire",
		"theme": "new-years",
		"imageURL": "solitaire-new-years-landscape.jpg",
		"linkURL": "http://www.newyearssolitaire.com/",
		"seasonal": true
	},
	{
		"gameType": "mahjong",
		"theme": "247",
		"imageURL": "mahjong-247-landscape.jpg",
		"linkURL": "https://www.247mahjong.com/",
		"seasonal": true
	},
	{
		"gameType": "mahjong",
		"theme": "winter",
		"imageURL": "mahjong-winter-landscape.jpg",
		"linkURL": "https://www.247mahjong.com/winter/",
		"seasonal": true
	},
	{
		"gameType": "mahjong",
		"theme": "valentines",
		"imageURL": "mahjong-valentines-landscape.jpg",
		"linkURL": "https://www.247mahjong.com/valentines/",
		"seasonal": true
	},
	{
		"gameType": "mahjong",
		"theme": "st-patricks",
		"imageURL": "mahjong-st-patricks-landscape.jpg",
		"linkURL": "https://www.247mahjong.com/st-patricks/",
		"seasonal": true
	},
	{
		"gameType": "mahjong",
		"theme": "easter",
		"imageURL": "mahjong-easter-landscape.jpg",
		"linkURL": "https://www.247mahjong.com/easter/",
		"seasonal": true
	},
	{
		"gameType": "mahjong",
		"theme": "cinco-de-mayo",
		"imageURL": "mahjong-cinco-de-mayo-landscape.jpg",
		"linkURL": "https://www.247mahjong.com/cinco-de-mayo/",
		"seasonal": true
	},
	{
		"gameType": "mahjong",
		"theme": "spring",
		"imageURL": "mahjong-spring-landscape.jpg",
		"linkURL": "https://www.247mahjong.com/spring/",
		"seasonal": true
	},
	{
		"gameType": "mahjong",
		"theme": "4th-of-july",
		"imageURL": "mahjong-4th-of-july-landscape.jpg",
		"linkURL": "https://www.247mahjong.com/4th-of-july/",
		"seasonal": true
	},
	{
		"gameType": "mahjong",
		"theme": "summer",
		"imageURL": "mahjong-summer-landscape.jpg",
		"linkURL": "https://www.247mahjong.com/summer/",
		"seasonal": true
	},
	{
		"gameType": "mahjong",
		"theme": "fall",
		"imageURL": "mahjong-fall-landscape.jpg",
		"linkURL": "https://www.247mahjong.com/fall/",
		"seasonal": true
	},
	{
		"gameType": "mahjong",
		"theme": "halloween",
		"imageURL": "mahjong-halloween-landscape.jpg",
		"linkURL": "https://www.247mahjong.com/halloween/",
		"seasonal": true
	},
	{
		"gameType": "mahjong",
		"theme": "thanksgiving",
		"imageURL": "mahjong-thanksgiving-landscape.jpg",
		"linkURL": "https://www.247mahjong.com/thanksgiving/",
		"seasonal": true
	},
	{
		"gameType": "mahjong",
		"theme": "christmas",
		"imageURL": "mahjong-christmas-landscape.jpg",
		"linkURL": "https://www.247mahjong.com/christmas/",
		"seasonal": true
	},
	{
		"gameType": "mahjong",
		"theme": "new-years",
		"imageURL": "mahjong-new-years-landscape.jpg",
		"linkURL": "https://www.247mahjong.com/new-years/",
		"seasonal": true
	},
	{
		"gameType": "sudoku",
		"theme": "247",
		"imageURL": "sudoku-247-landscape.jpg",
		"linkURL": "https://www.247sudoku.com/",
		"seasonal": true
	},
	{
		"gameType": "sudoku",
		"theme": "winter",
		"imageURL": "sudoku-winter-landscape.jpg",
		"linkURL": "https://www.247sudoku.com/winter/",
		"seasonal": true
	},
	{
		"gameType": "sudoku",
		"theme": "valentines",
		"imageURL": "sudoku-valentines-landscape.jpg",
		"linkURL": "https://www.247sudoku.com/valentines/",
		"seasonal": true
	},
	{
		"gameType": "sudoku",
		"theme": "st-patricks",
		"imageURL": "sudoku-st-patricks-landscape.jpg",
		"linkURL": "https://www.247sudoku.com/st-patricks/",
		"seasonal": true
	},
	{
		"gameType": "sudoku",
		"theme": "easter",
		"imageURL": "sudoku-easter-landscape.jpg",
		"linkURL": "https://www.247sudoku.com/easter/",
		"seasonal": true
	},
	{
		"gameType": "sudoku",
		"theme": "cinco-de-mayo",
		"imageURL": "sudoku-cinco-de-mayo-landscape.jpg",
		"linkURL": "https://www.247sudoku.com/cinco-de-mayo/",
		"seasonal": true
	},
	{
		"gameType": "sudoku",
		"theme": "spring",
		"imageURL": "sudoku-spring-landscape.jpg",
		"linkURL": "https://www.247sudoku.com/spring/",
		"seasonal": true
	},
	{
		"gameType": "sudoku",
		"theme": "4th-of-july",
		"imageURL": "sudoku-4th-of-july-landscape.jpg",
		"linkURL": "https://www.247sudoku.com/4th-of-july/",
		"seasonal": true
	},
	{
		"gameType": "sudoku",
		"theme": "summer",
		"imageURL": "sudoku-summer-landscape.jpg",
		"linkURL": "https://www.247sudoku.com/summer/",
		"seasonal": true
	},
	{
		"gameType": "sudoku",
		"theme": "fall",
		"imageURL": "sudoku-fall-landscape.jpg",
		"linkURL": "https://www.247sudoku.com/fall/",
		"seasonal": true
	},
	{
		"gameType": "sudoku",
		"theme": "halloween",
		"imageURL": "sudoku-halloween-landscape.jpg",
		"linkURL": "https://www.247sudoku.com/halloween/",
		"seasonal": true
	},
	{
		"gameType": "sudoku",
		"theme": "thanksgiving",
		"imageURL": "sudoku-thanksgiving-landscape.jpg",
		"linkURL": "https://www.247sudoku.com/thanksgiving/",
		"seasonal": true
	},
	{
		"gameType": "sudoku",
		"theme": "christmas",
		"imageURL": "sudoku-christmas-landscape.jpg",
		"linkURL": "https://www.247sudoku.com/christmas/",
		"seasonal": true
	},
	{
		"gameType": "sudoku",
		"theme": "new-years",
		"imageURL": "sudoku-new-years-landscape.jpg",
		"linkURL": "https://www.247sudoku.com/new-years/",
		"seasonal": true
	},
	{
		"gameType": "minesweeper",
		"theme": "247",
		"imageURL": "minesweeper-247-landscape.jpg",
		"linkURL": "https://www.247minesweeper.com/",
		"seasonal": true
	},
	{
		"gameType": "minesweeper",
		"theme": "winter",
		"imageURL": "minesweeper-winter-landscape.jpg",
		"linkURL": "https://www.247minesweeper.com/winter/",
		"seasonal": true
	},
	{
		"gameType": "minesweeper",
		"theme": "valentines",
		"imageURL": "minesweeper-valentines-landscape.jpg",
		"linkURL": "https://www.247minesweeper.com/valentines/",
		"seasonal": true
	},
	{
		"gameType": "minesweeper",
		"theme": "st-patricks",
		"imageURL": "minesweeper-st-patricks-landscape.jpg",
		"linkURL": "https://www.247minesweeper.com/st-patricks/",
		"seasonal": true
	},
	{
		"gameType": "minesweeper",
		"theme": "easter",
		"imageURL": "minesweeper-easter-landscape.jpg",
		"linkURL": "https://www.247minesweeper.com/easter/",
		"seasonal": true
	},
	{
		"gameType": "minesweeper",
		"theme": "cinco-de-mayo",
		"imageURL": "minesweeper-cinco-de-mayo-landscape.jpg",
		"linkURL": "https://www.247minesweeper.com/cinco-de-mayo/",
		"seasonal": true
	},
	{
		"gameType": "minesweeper",
		"theme": "spring",
		"imageURL": "minesweeper-spring-landscape.jpg",
		"linkURL": "https://www.247minesweeper.com/spring/",
		"seasonal": true
	},
	{
		"gameType": "minesweeper",
		"theme": "4th-of-july",
		"imageURL": "minesweeper-4th-of-july-landscape.jpg",
		"linkURL": "https://www.247minesweeper.com/4th-of-july/",
		"seasonal": true
	},
	{
		"gameType": "minesweeper",
		"theme": "summer",
		"imageURL": "minesweeper-summer-landscape.jpg",
		"linkURL": "https://www.247minesweeper.com/summer/",
		"seasonal": true
	},
	{
		"gameType": "minesweeper",
		"theme": "fall",
		"imageURL": "minesweeper-fall-landscape.jpg",
		"linkURL": "https://www.247minesweeper.com/fall/",
		"seasonal": true
	},
	{
		"gameType": "minesweeper",
		"theme": "halloween",
		"imageURL": "minesweeper-halloween-landscape.jpg",
		"linkURL": "https://www.247minesweeper.com/halloween/",
		"seasonal": true
	},
	{
		"gameType": "minesweeper",
		"theme": "thanksgiving",
		"imageURL": "minesweeper-thanksgiving-landscape.jpg",
		"linkURL": "https://www.247minesweeper.com/thanksgiving/",
		"seasonal": true
	},
	{
		"gameType": "minesweeper",
		"theme": "christmas",
		"imageURL": "minesweeper-christmas-landscape.jpg",
		"linkURL": "https://www.247minesweeper.com/christmas/",
		"seasonal": true
	},
	{
		"gameType": "minesweeper",
		"theme": "new-years",
		"imageURL": "minesweeper-new-years-landscape.jpg",
		"linkURL": "https://www.247minesweeper.com/new-years/",
		"seasonal": true
	},
	{
		"gameType": "word-search",
		"theme": "247",
		"imageURL": "word-search-247-landscape.jpg",
		"linkURL": "https://www.247wordsearch.com/",
		"seasonal": true
	},
	{
		"gameType": "word-search",
		"theme": "winter",
		"imageURL": "word-search-winter-landscape.jpg",
		"linkURL": "https://www.247wordsearch.com/winter/",
		"seasonal": true
	},
	{
		"gameType": "word-search",
		"theme": "valentines",
		"imageURL": "word-search-valentines-landscape.jpg",
		"linkURL": "https://www.247wordsearch.com/valentines/",
		"seasonal": true
	},
	{
		"gameType": "word-search",
		"theme": "st-patricks",
		"imageURL": "word-search-st-patricks-landscape.jpg",
		"linkURL": "https://www.247wordsearch.com/st-patricks/",
		"seasonal": true
	},
	{
		"gameType": "word-search",
		"theme": "easter",
		"imageURL": "word-search-easter-landscape.jpg",
		"linkURL": "https://www.247wordsearch.com/easter/",
		"seasonal": true
	},
	{
		"gameType": "word-search",
		"theme": "cinco-de-mayo",
		"imageURL": "word-search-cinco-de-mayo-landscape.jpg",
		"linkURL": "https://www.247wordsearch.com/cinco-de-mayo/",
		"seasonal": true
	},
	{
		"gameType": "word-search",
		"theme": "spring",
		"imageURL": "word-search-spring-landscape.jpg",
		"linkURL": "https://www.247wordsearch.com/spring/",
		"seasonal": true
	},
	{
		"gameType": "word-search",
		"theme": "4th-of-july",
		"imageURL": "word-search-4th-of-july-landscape.jpg",
		"linkURL": "https://www.247wordsearch.com/4th-of-july/",
		"seasonal": true
	},
	{
		"gameType": "word-search",
		"theme": "summer",
		"imageURL": "word-search-summer-landscape.jpg",
		"linkURL": "https://www.247wordsearch.com/summer/",
		"seasonal": true
	},
	{
		"gameType": "word-search",
		"theme": "fall",
		"imageURL": "word-search-fall-landscape.jpg",
		"linkURL": "https://www.247wordsearch.com/fall/",
		"seasonal": true
	},
	{
		"gameType": "word-search",
		"theme": "halloween",
		"imageURL": "word-search-halloween-landscape.jpg",
		"linkURL": "https://www.247wordsearch.com/halloween/",
		"seasonal": true
	},
	{
		"gameType": "word-search",
		"theme": "thanksgiving",
		"imageURL": "word-search-thanksgiving-landscape.jpg",
		"linkURL": "https://www.247wordsearch.com/thanksgiving/",
		"seasonal": true
	},
	{
		"gameType": "word-search",
		"theme": "christmas",
		"imageURL": "word-search-christmas-landscape.jpg",
		"linkURL": "https://www.247wordsearch.com/christmas/",
		"seasonal": true
	},
	{
		"gameType": "word-search",
		"theme": "new-years",
		"imageURL": "word-search-new-years-landscape.jpg",
		"linkURL": "https://www.247wordsearch.com/new-years/",
		"seasonal": true
	},
	{
		"gameType": "backgammon",
		"theme": "247",
		"imageURL": "backgammon-247-landscape.jpg",
		"linkURL": "https://www.247backgammon.org/",
		"seasonal": true
	},
	{
		"gameType": "backgammon",
		"theme": "winter",
		"imageURL": "backgammon-winter-landscape.jpg",
		"linkURL": "https://www.247backgammon.org/winter/",
		"seasonal": true
	},
	{
		"gameType": "backgammon",
		"theme": "valentines",
		"imageURL": "backgammon-valentines-landscape.jpg",
		"linkURL": "https://www.247backgammon.org/valentines/",
		"seasonal": true
	},
	{
		"gameType": "backgammon",
		"theme": "st-patricks",
		"imageURL": "backgammon-st-patricks-landscape.jpg",
		"linkURL": "https://www.247backgammon.org/st-patricks/",
		"seasonal": true
	},
	{
		"gameType": "backgammon",
		"theme": "easter",
		"imageURL": "backgammon-easter-landscape.jpg",
		"linkURL": "https://www.247backgammon.org/easter/",
		"seasonal": true
	},
	{
		"gameType": "backgammon",
		"theme": "cinco-de-mayo",
		"imageURL": "backgammon-cinco-de-mayo-landscape.jpg",
		"linkURL": "https://www.247backgammon.org/cinco-de-mayo/",
		"seasonal": true
	},
	{
		"gameType": "backgammon",
		"theme": "spring",
		"imageURL": "backgammon-spring-landscape.jpg",
		"linkURL": "https://www.247backgammon.org/spring/",
		"seasonal": true
	},
	{
		"gameType": "backgammon",
		"theme": "4th-of-july",
		"imageURL": "backgammon-4th-of-july-landscape.jpg",
		"linkURL": "https://www.247backgammon.org/4th-of-july/",
		"seasonal": true
	},
	{
		"gameType": "backgammon",
		"theme": "summer",
		"imageURL": "backgammon-summer-landscape.jpg",
		"linkURL": "https://www.247backgammon.org/summer/",
		"seasonal": true
	},
	{
		"gameType": "backgammon",
		"theme": "fall",
		"imageURL": "backgammon-fall-landscape.jpg",
		"linkURL": "https://www.247backgammon.org/fall/",
		"seasonal": true
	},
	{
		"gameType": "backgammon",
		"theme": "halloween",
		"imageURL": "backgammon-halloween-landscape.jpg",
		"linkURL": "https://www.247backgammon.org/halloween/",
		"seasonal": true
	},
	{
		"gameType": "backgammon",
		"theme": "thanksgiving",
		"imageURL": "backgammon-thanksgiving-landscape.jpg",
		"linkURL": "https://www.247backgammon.org/thanksgiving/",
		"seasonal": true
	},
	{
		"gameType": "backgammon",
		"theme": "christmas",
		"imageURL": "backgammon-christmas-landscape.jpg",
		"linkURL": "https://www.247backgammon.org/christmas/",
		"seasonal": true
	},
	{
		"gameType": "backgammon",
		"theme": "new-years",
		"imageURL": "backgammon-new-years-landscape.jpg",
		"linkURL": "https://www.247backgammon.org/new-years/",
		"seasonal": true
	},
	{
		"gameType": "blackjack",
		"theme": "247",
		"imageURL": "blackjack-247-landscape.jpg",
		"linkURL": "https://www.247blackjack.com/",
		"seasonal": true
	},
	{
		"gameType": "blackjack",
		"theme": "winter",
		"imageURL": "blackjack-winter-landscape.jpg",
		"linkURL": "https://www.247blackjack.com/winter/",
		"seasonal": true
	},
	{
		"gameType": "blackjack",
		"theme": "valentines",
		"imageURL": "blackjack-valentines-landscape.jpg",
		"linkURL": "https://www.247blackjack.com/valentines/",
		"seasonal": true
	},
	{
		"gameType": "blackjack",
		"theme": "st-patricks",
		"imageURL": "blackjack-st-patricks-landscape.jpg",
		"linkURL": "https://www.247blackjack.com/st-patricks/",
		"seasonal": true
	},
	{
		"gameType": "blackjack",
		"theme": "easter",
		"imageURL": "blackjack-easter-landscape.jpg",
		"linkURL": "https://www.247blackjack.com/easter/",
		"seasonal": true
	},
	{
		"gameType": "blackjack",
		"theme": "cinco-de-mayo",
		"imageURL": "blackjack-cinco-de-mayo-landscape.jpg",
		"linkURL": "https://www.247blackjack.com/cinco-de-mayo/",
		"seasonal": true
	},
	{
		"gameType": "blackjack",
		"theme": "spring",
		"imageURL": "blackjack-spring-landscape.jpg",
		"linkURL": "https://www.247blackjack.com/spring/",
		"seasonal": true
	},
	{
		"gameType": "blackjack",
		"theme": "4th-of-july",
		"imageURL": "blackjack-4th-of-july-landscape.jpg",
		"linkURL": "https://www.247blackjack.com/4th-of-july/",
		"seasonal": true
	},
	{
		"gameType": "blackjack",
		"theme": "summer",
		"imageURL": "blackjack-summer-landscape.jpg",
		"linkURL": "https://www.247blackjack.com/summer/",
		"seasonal": true
	},
	{
		"gameType": "blackjack",
		"theme": "fall",
		"imageURL": "blackjack-fall-landscape.jpg",
		"linkURL": "https://www.247blackjack.com/fall/",
		"seasonal": true
	},
	{
		"gameType": "blackjack",
		"theme": "halloween",
		"imageURL": "blackjack-halloween-landscape.jpg",
		"linkURL": "https://www.247blackjack.com/halloween/",
		"seasonal": true
	},
	{
		"gameType": "blackjack",
		"theme": "thanksgiving",
		"imageURL": "blackjack-thanksgiving-landscape.jpg",
		"linkURL": "https://www.247blackjack.com/thanksgiving/",
		"seasonal": true
	},
	{
		"gameType": "blackjack",
		"theme": "christmas",
		"imageURL": "blackjack-christmas-landscape.jpg",
		"linkURL": "https://www.247blackjack.com/christmas/",
		"seasonal": true
	},
	{
		"gameType": "blackjack",
		"theme": "new-years",
		"imageURL": "blackjack-new-years-landscape.jpg",
		"linkURL": "https://www.247blackjack.com/new-years/",
		"seasonal": true
	},
	{
		"gameType": "hearts",
		"theme": "247",
		"imageURL": "hearts-247-landscape.jpg",
		"linkURL": "https://www.247hearts.com/",
		"seasonal": true
	},
	{
		"gameType": "hearts",
		"theme": "winter",
		"imageURL": "hearts-winter-landscape.jpg",
		"linkURL": "https://www.247hearts.com/winter/",
		"seasonal": true
	},
	{
		"gameType": "hearts",
		"theme": "valentines",
		"imageURL": "hearts-valentines-landscape.jpg",
		"linkURL": "https://www.247hearts.com/valentines/",
		"seasonal": true
	},
	{
		"gameType": "hearts",
		"theme": "st-patricks",
		"imageURL": "hearts-st-patricks-landscape.jpg",
		"linkURL": "https://www.247hearts.com/st-patricks/",
		"seasonal": true
	},
	{
		"gameType": "hearts",
		"theme": "easter",
		"imageURL": "hearts-easter-landscape.jpg",
		"linkURL": "https://www.247hearts.com/easter/",
		"seasonal": true
	},
	{
		"gameType": "hearts",
		"theme": "cinco-de-mayo",
		"imageURL": "hearts-cinco-de-mayo-landscape.jpg",
		"linkURL": "https://www.247hearts.com/cinco-de-mayo/",
		"seasonal": true
	},
	{
		"gameType": "hearts",
		"theme": "spring",
		"imageURL": "hearts-spring-landscape.jpg",
		"linkURL": "https://www.247hearts.com/spring/",
		"seasonal": true
	},
	{
		"gameType": "hearts",
		"theme": "4th-of-july",
		"imageURL": "hearts-4th-of-july-landscape.jpg",
		"linkURL": "https://www.247hearts.com/4th-of-july/",
		"seasonal": true
	},
	{
		"gameType": "hearts",
		"theme": "summer",
		"imageURL": "hearts-summer-landscape.jpg",
		"linkURL": "https://www.247hearts.com/summer/",
		"seasonal": true
	},
	{
		"gameType": "hearts",
		"theme": "fall",
		"imageURL": "hearts-fall-landscape.jpg",
		"linkURL": "https://www.247hearts.com/fall/",
		"seasonal": true
	},
	{
		"gameType": "hearts",
		"theme": "halloween",
		"imageURL": "hearts-halloween-landscape.jpg",
		"linkURL": "https://www.247hearts.com/halloween/",
		"seasonal": true
	},
	{
		"gameType": "hearts",
		"theme": "thanksgiving",
		"imageURL": "hearts-thanksgiving-landscape.jpg",
		"linkURL": "https://www.247hearts.com/thanksgiving/",
		"seasonal": true
	},
	{
		"gameType": "hearts",
		"theme": "christmas",
		"imageURL": "hearts-christmas-landscape.jpg",
		"linkURL": "https://www.247hearts.com/christmas/",
		"seasonal": true
	},
	{
		"gameType": "hearts",
		"theme": "new-years",
		"imageURL": "hearts-new-years-landscape.jpg",
		"linkURL": "https://www.247hearts.com/new-years/",
		"seasonal": true
	},
	{
		"gameType": "bridge",
		"theme": "247",
		"imageURL": "bridge-247-landscape.jpg",
		"linkURL": "https://www.247bridge.com/",
		"seasonal": true
	},
	{
		"gameType": "bridge",
		"theme": "winter",
		"imageURL": "bridge-winter-landscape.jpg",
		"linkURL": "https://www.247bridge.com/winter/",
		"seasonal": true
	},
	{
		"gameType": "bridge",
		"theme": "valentines",
		"imageURL": "bridge-valentines-landscape.jpg",
		"linkURL": "https://www.247bridge.com/valentines/",
		"seasonal": true
	},
	{
		"gameType": "bridge",
		"theme": "st-patricks",
		"imageURL": "bridge-st-patricks-landscape.jpg",
		"linkURL": "https://www.247bridge.com/st-patricks/",
		"seasonal": true
	},
	{
		"gameType": "bridge",
		"theme": "easter",
		"imageURL": "bridge-easter-landscape.jpg",
		"linkURL": "https://www.247bridge.com/easter/",
		"seasonal": true
	},
	{
		"gameType": "bridge",
		"theme": "cinco-de-mayo",
		"imageURL": "bridge-cinco-de-mayo-landscape.jpg",
		"linkURL": "https://www.247bridge.com/cinco-de-mayo/",
		"seasonal": true
	},
	{
		"gameType": "bridge",
		"theme": "spring",
		"imageURL": "bridge-spring-landscape.jpg",
		"linkURL": "https://www.247bridge.com/spring/",
		"seasonal": true
	},
	{
		"gameType": "bridge",
		"theme": "4th-of-july",
		"imageURL": "bridge-4th-of-july-landscape.jpg",
		"linkURL": "https://www.247bridge.com/4th-of-july/",
		"seasonal": true
	},
	{
		"gameType": "bridge",
		"theme": "summer",
		"imageURL": "bridge-summer-landscape.jpg",
		"linkURL": "https://www.247bridge.com/summer/",
		"seasonal": true
	},
	{
		"gameType": "bridge",
		"theme": "fall",
		"imageURL": "bridge-fall-landscape.jpg",
		"linkURL": "https://www.247bridge.com/fall/",
		"seasonal": true
	},
	{
		"gameType": "bridge",
		"theme": "halloween",
		"imageURL": "bridge-halloween-landscape.jpg",
		"linkURL": "https://www.247bridge.com/halloween/",
		"seasonal": true
	},
	{
		"gameType": "bridge",
		"theme": "thanksgiving",
		"imageURL": "bridge-thanksgiving-landscape.jpg",
		"linkURL": "https://www.247bridge.com/thanksgiving/",
		"seasonal": true
	},
	{
		"gameType": "bridge",
		"theme": "christmas",
		"imageURL": "bridge-christmas-landscape.jpg",
		"linkURL": "https://www.247bridge.com/christmas/",
		"seasonal": true
	},
	{
		"gameType": "bridge",
		"theme": "new-years",
		"imageURL": "bridge-new-years-landscape.jpg",
		"linkURL": "https://www.247bridge.com/new-years/",
		"seasonal": true
	},
	{
		"gameType": "spades",
		"theme": "247",
		"imageURL": "spades-247-landscape.jpg",
		"linkURL": "https://www.247spades.com/",
		"seasonal": true
	},
	{
		"gameType": "spades",
		"theme": "winter",
		"imageURL": "spades-winter-landscape.jpg",
		"linkURL": "https://www.247spades.com/winter/",
		"seasonal": true
	},
	{
		"gameType": "spades",
		"theme": "valentines",
		"imageURL": "spades-valentines-landscape.jpg",
		"linkURL": "https://www.247spades.com/valentines/",
		"seasonal": true
	},
	{
		"gameType": "spades",
		"theme": "st-patricks",
		"imageURL": "spades-st-patricks-landscape.jpg",
		"linkURL": "https://www.247spades.com/st-patricks/",
		"seasonal": true
	},
	{
		"gameType": "spades",
		"theme": "easter",
		"imageURL": "spades-easter-landscape.jpg",
		"linkURL": "https://www.247spades.com/easter/",
		"seasonal": true
	},
	{
		"gameType": "spades",
		"theme": "cinco-de-mayo",
		"imageURL": "spades-cinco-de-mayo-landscape.jpg",
		"linkURL": "https://www.247spades.com/cinco-de-mayo/",
		"seasonal": true
	},
	{
		"gameType": "spades",
		"theme": "spring",
		"imageURL": "spades-spring-landscape.jpg",
		"linkURL": "https://www.247spades.com/spring/",
		"seasonal": true
	},
	{
		"gameType": "spades",
		"theme": "4th-of-july",
		"imageURL": "spades-4th-of-july-landscape.jpg",
		"linkURL": "https://www.247spades.com/4th-of-july/",
		"seasonal": true
	},
	{
		"gameType": "spades",
		"theme": "summer",
		"imageURL": "spades-summer-landscape.jpg",
		"linkURL": "https://www.247spades.com/summer/",
		"seasonal": true
	},
	{
		"gameType": "spades",
		"theme": "fall",
		"imageURL": "spades-fall-landscape.jpg",
		"linkURL": "https://www.247spades.com/fall/",
		"seasonal": true
	},
	{
		"gameType": "spades",
		"theme": "halloween",
		"imageURL": "spades-halloween-landscape.jpg",
		"linkURL": "https://www.247spades.com/halloween/",
		"seasonal": true
	},
	{
		"gameType": "spades",
		"theme": "thanksgiving",
		"imageURL": "spades-thanksgiving-landscape.jpg",
		"linkURL": "https://www.247spades.com/thanksgiving/",
		"seasonal": true
	},
	{
		"gameType": "spades",
		"theme": "christmas",
		"imageURL": "spades-christmas-landscape.jpg",
		"linkURL": "https://www.247spades.com/christmas/",
		"seasonal": true
	},
	{
		"gameType": "spades",
		"theme": "new-years",
		"imageURL": "spades-new-years-landscape.jpg",
		"linkURL": "https://www.247spades.com/new-years/",
		"seasonal": true
	},
	{
		"gameType": "checkers",
		"theme": "247",
		"imageURL": "checkers-247-landscape.jpg",
		"linkURL": "https://www.247checkers.com/",
		"seasonal": true
	},
	{
		"gameType": "checkers",
		"theme": "winter",
		"imageURL": "checkers-winter-landscape.jpg",
		"linkURL": "https://www.247checkers.com/winter/",
		"seasonal": true
	},
	{
		"gameType": "checkers",
		"theme": "valentines",
		"imageURL": "checkers-valentines-landscape.jpg",
		"linkURL": "https://www.247checkers.com/valentines/",
		"seasonal": true
	},
	{
		"gameType": "checkers",
		"theme": "st-patricks",
		"imageURL": "checkers-st-patricks-landscape.jpg",
		"linkURL": "https://www.247checkers.com/st-patricks/",
		"seasonal": true
	},
	{
		"gameType": "checkers",
		"theme": "easter",
		"imageURL": "checkers-easter-landscape.jpg",
		"linkURL": "https://www.247checkers.com/easter/",
		"seasonal": true
	},
	{
		"gameType": "checkers",
		"theme": "cinco-de-mayo",
		"imageURL": "checkers-cinco-de-mayo-landscape.jpg",
		"linkURL": "https://www.247checkers.com/cinco-de-mayo/",
		"seasonal": true
	},
	{
		"gameType": "checkers",
		"theme": "spring",
		"imageURL": "checkers-spring-landscape.jpg",
		"linkURL": "https://www.247checkers.com/spring/",
		"seasonal": true
	},
	{
		"gameType": "checkers",
		"theme": "4th-of-july",
		"imageURL": "checkers-4th-of-july-landscape.jpg",
		"linkURL": "https://www.247checkers.com/4th-of-july/",
		"seasonal": true
	},
	{
		"gameType": "checkers",
		"theme": "summer",
		"imageURL": "checkers-summer-landscape.jpg",
		"linkURL": "https://www.247checkers.com/summer/",
		"seasonal": true
	},
	{
		"gameType": "checkers",
		"theme": "fall",
		"imageURL": "checkers-fall-landscape.jpg",
		"linkURL": "https://www.247checkers.com/fall/",
		"seasonal": true
	},
	{
		"gameType": "checkers",
		"theme": "halloween",
		"imageURL": "checkers-halloween-landscape.jpg",
		"linkURL": "https://www.247checkers.com/halloween/",
		"seasonal": true
	},
	{
		"gameType": "checkers",
		"theme": "thanksgiving",
		"imageURL": "checkers-thanksgiving-landscape.jpg",
		"linkURL": "https://www.247checkers.com/thanksgiving/",
		"seasonal": true
	},
	{
		"gameType": "checkers",
		"theme": "christmas",
		"imageURL": "checkers-christmas-landscape.jpg",
		"linkURL": "https://www.247checkers.com/christmas/",
		"seasonal": true
	},
	{
		"gameType": "checkers",
		"theme": "new-years",
		"imageURL": "checkers-new-years-landscape.jpg",
		"linkURL": "https://www.247checkers.com/new-years/",
		"seasonal": true
	},
	{
		"gameType": "chess",
		"theme": "247",
		"imageURL": "chess-247-landscape.jpg",
		"linkURL": "https://www.247chess.com/",
		"seasonal": true
	},
	{
		"gameType": "chess",
		"theme": "winter",
		"imageURL": "chess-winter-landscape.jpg",
		"linkURL": "https://www.247chess.com/winter/",
		"seasonal": true
	},
	{
		"gameType": "chess",
		"theme": "valentines",
		"imageURL": "chess-valentines-landscape.jpg",
		"linkURL": "https://www.247chess.com/valentines/",
		"seasonal": true
	},
	{
		"gameType": "chess",
		"theme": "st-patricks",
		"imageURL": "chess-st-patricks-landscape.jpg",
		"linkURL": "https://www.247chess.com/st-patricks/",
		"seasonal": true
	},
	{
		"gameType": "chess",
		"theme": "easter",
		"imageURL": "chess-easter-landscape.jpg",
		"linkURL": "https://www.247chess.com/easter/",
		"seasonal": true
	},
	{
		"gameType": "chess",
		"theme": "cinco-de-mayo",
		"imageURL": "chess-cinco-de-mayo-landscape.jpg",
		"linkURL": "https://www.247chess.com/cinco-de-mayo/",
		"seasonal": true
	},
	{
		"gameType": "chess",
		"theme": "spring",
		"imageURL": "chess-spring-landscape.jpg",
		"linkURL": "https://www.247chess.com/spring/",
		"seasonal": true
	},
	{
		"gameType": "chess",
		"theme": "4th-of-july",
		"imageURL": "chess-4th-of-july-landscape.jpg",
		"linkURL": "https://www.247chess.com/4th-of-july/",
		"seasonal": true
	},
	{
		"gameType": "chess",
		"theme": "summer",
		"imageURL": "chess-summer-landscape.jpg",
		"linkURL": "https://www.247chess.com/summer/",
		"seasonal": true
	},
	{
		"gameType": "chess",
		"theme": "fall",
		"imageURL": "chess-fall-landscape.jpg",
		"linkURL": "https://www.247chess.com/fall/",
		"seasonal": true
	},
	{
		"gameType": "chess",
		"theme": "halloween",
		"imageURL": "chess-halloween-landscape.jpg",
		"linkURL": "https://www.247chess.com/halloween/",
		"seasonal": true
	},
	{
		"gameType": "chess",
		"theme": "thanksgiving",
		"imageURL": "chess-thanksgiving-landscape.jpg",
		"linkURL": "https://www.247chess.com/thanksgiving/",
		"seasonal": true
	},
	{
		"gameType": "chess",
		"theme": "christmas",
		"imageURL": "chess-christmas-landscape.jpg",
		"linkURL": "https://www.247chess.com/christmas/",
		"seasonal": true
	},
	{
		"gameType": "chess",
		"theme": "new-years",
		"imageURL": "chess-new-years-landscape.jpg",
		"linkURL": "https://www.247chess.com/new-years/",
		"seasonal": true
	},
	{
		"gameType": "roulette",
		"theme": "247",
		"imageURL": "roulette-247-landscape.jpg",
		"linkURL": "https://www.247roulette.org/",
		"seasonal": true
	},
	{
		"gameType": "roulette",
		"theme": "winter",
		"imageURL": "roulette-winter-landscape.jpg",
		"linkURL": "https://www.247roulette.org/winter/",
		"seasonal": true
	},
	{
		"gameType": "roulette",
		"theme": "valentines",
		"imageURL": "roulette-valentines-landscape.jpg",
		"linkURL": "https://www.247roulette.org/valentines/",
		"seasonal": true
	},
	{
		"gameType": "roulette",
		"theme": "st-patricks",
		"imageURL": "roulette-st-patricks-landscape.jpg",
		"linkURL": "https://www.247roulette.org/st-patricks/",
		"seasonal": true
	},
	{
		"gameType": "roulette",
		"theme": "easter",
		"imageURL": "roulette-easter-landscape.jpg",
		"linkURL": "https://www.247roulette.org/easter/",
		"seasonal": true
	},
	{
		"gameType": "roulette",
		"theme": "cinco-de-mayo",
		"imageURL": "roulette-cinco-de-mayo-landscape.jpg",
		"linkURL": "https://www.247roulette.org/cinco-de-mayo/",
		"seasonal": true
	},
	{
		"gameType": "roulette",
		"theme": "spring",
		"imageURL": "roulette-spring-landscape.jpg",
		"linkURL": "https://www.247roulette.org/spring/",
		"seasonal": true
	},
	{
		"gameType": "roulette",
		"theme": "4th-of-july",
		"imageURL": "roulette-4th-of-july-landscape.jpg",
		"linkURL": "https://www.247roulette.org/4th-of-july/",
		"seasonal": true
	},
	{
		"gameType": "roulette",
		"theme": "summer",
		"imageURL": "roulette-summer-landscape.jpg",
		"linkURL": "https://www.247roulette.org/summer/",
		"seasonal": true
	},
	{
		"gameType": "roulette",
		"theme": "fall",
		"imageURL": "roulette-fall-landscape.jpg",
		"linkURL": "https://www.247roulette.org/fall/",
		"seasonal": true
	},
	{
		"gameType": "roulette",
		"theme": "halloween",
		"imageURL": "roulette-halloween-landscape.jpg",
		"linkURL": "https://www.247roulette.org/halloween/",
		"seasonal": true
	},
	{
		"gameType": "roulette",
		"theme": "thanksgiving",
		"imageURL": "roulette-thanksgiving-landscape.jpg",
		"linkURL": "https://www.247roulette.org/thanksgiving/",
		"seasonal": true
	},
	{
		"gameType": "roulette",
		"theme": "christmas",
		"imageURL": "roulette-christmas-landscape.jpg",
		"linkURL": "https://www.247roulette.org/christmas/",
		"seasonal": true
	},
	{
		"gameType": "roulette",
		"theme": "new-years",
		"imageURL": "roulette-new-years-landscape.jpg",
		"linkURL": "https://www.247roulette.org/new-years/",
		"seasonal": true
	},
	{
		"gameType": "slots",
		"theme": "247",
		"imageURL": "slots-247-landscape.jpg",
		"linkURL": "https://www.247slots.org/",
		"seasonal": true
	},
	{
		"gameType": "slots",
		"theme": "winter",
		"imageURL": "slots-winter-landscape.jpg",
		"linkURL": "https://www.247slots.org/winter/",
		"seasonal": true
	},
	{
		"gameType": "slots",
		"theme": "valentines",
		"imageURL": "slots-valentines-landscape.jpg",
		"linkURL": "https://www.247slots.org/valentines/",
		"seasonal": true
	},
	{
		"gameType": "slots",
		"theme": "st-patricks",
		"imageURL": "slots-st-patricks-landscape.jpg",
		"linkURL": "https://www.247slots.org/st-patricks/",
		"seasonal": true
	},
	{
		"gameType": "slots",
		"theme": "easter",
		"imageURL": "slots-easter-landscape.jpg",
		"linkURL": "https://www.247slots.org/easter/",
		"seasonal": true
	},
	{
		"gameType": "slots",
		"theme": "cinco-de-mayo",
		"imageURL": "slots-cinco-de-mayo-landscape.jpg",
		"linkURL": "https://www.247slots.org/cinco-de-mayo/",
		"seasonal": true
	},
	{
		"gameType": "slots",
		"theme": "spring",
		"imageURL": "slots-spring-landscape.jpg",
		"linkURL": "https://www.247slots.org/spring/",
		"seasonal": true
	},
	{
		"gameType": "slots",
		"theme": "4th-of-july",
		"imageURL": "slots-4th-of-july-landscape.jpg",
		"linkURL": "https://www.247slots.org/4th-of-july/",
		"seasonal": true
	},
	{
		"gameType": "slots",
		"theme": "summer",
		"imageURL": "slots-summer-landscape.jpg",
		"linkURL": "https://www.247slots.org/summer/",
		"seasonal": true
	},
	{
		"gameType": "slots",
		"theme": "fall",
		"imageURL": "slots-fall-landscape.jpg",
		"linkURL": "https://www.247slots.org/fall/",
		"seasonal": true
	},
	{
		"gameType": "slots",
		"theme": "halloween",
		"imageURL": "slots-halloween-landscape.jpg",
		"linkURL": "https://www.247slots.org/halloween/",
		"seasonal": true
	},
	{
		"gameType": "slots",
		"theme": "thanksgiving",
		"imageURL": "slots-thanksgiving-landscape.jpg",
		"linkURL": "https://www.247slots.org/thanksgiving/",
		"seasonal": true
	},
	{
		"gameType": "slots",
		"theme": "christmas",
		"imageURL": "slots-christmas-landscape.jpg",
		"linkURL": "https://www.247slots.org/christmas/",
		"seasonal": true
	},
	{
		"gameType": "slots",
		"theme": "new-years",
		"imageURL": "slots-new-years-landscape.jpg",
		"linkURL": "https://www.247slots.org/new-years/",
		"seasonal": true
	},
	{
		"gameType": "video-poker",
		"theme": "247",
		"imageURL": "video-poker-247-landscape.jpg",
		"linkURL": "https://www.247videopoker.org/",
		"seasonal": true
	},
	{
		"gameType": "video-poker",
		"theme": "winter",
		"imageURL": "video-poker-winter-landscape.jpg",
		"linkURL": "https://www.247videopoker.org/winter/",
		"seasonal": true
	},
	{
		"gameType": "video-poker",
		"theme": "valentines",
		"imageURL": "video-poker-valentines-landscape.jpg",
		"linkURL": "https://www.247videopoker.org/valentines/",
		"seasonal": true
	},
	{
		"gameType": "video-poker",
		"theme": "st-patricks",
		"imageURL": "video-poker-st-patricks-landscape.jpg",
		"linkURL": "https://www.247videopoker.org/st-patricks/",
		"seasonal": true
	},
	{
		"gameType": "video-poker",
		"theme": "easter",
		"imageURL": "video-poker-easter-landscape.jpg",
		"linkURL": "https://www.247videopoker.org/easter/",
		"seasonal": true
	},
	{
		"gameType": "video-poker",
		"theme": "cinco-de-mayo",
		"imageURL": "video-poker-cinco-de-mayo-landscape.jpg",
		"linkURL": "https://www.247videopoker.org/cinco-de-mayo/",
		"seasonal": true
	},
	{
		"gameType": "video-poker",
		"theme": "spring",
		"imageURL": "video-poker-spring-landscape.jpg",
		"linkURL": "https://www.247videopoker.org/spring/",
		"seasonal": true
	},
	{
		"gameType": "video-poker",
		"theme": "4th-of-july",
		"imageURL": "video-poker-4th-of-july-landscape.jpg",
		"linkURL": "https://www.247videopoker.org/4th-of-july/",
		"seasonal": true
	},
	{
		"gameType": "video-poker",
		"theme": "summer",
		"imageURL": "video-poker-summer-landscape.jpg",
		"linkURL": "https://www.247videopoker.org/summer/",
		"seasonal": true
	},
	{
		"gameType": "video-poker",
		"theme": "fall",
		"imageURL": "video-poker-fall-landscape.jpg",
		"linkURL": "https://www.247videopoker.org/fall/",
		"seasonal": true
	},
	{
		"gameType": "video-poker",
		"theme": "halloween",
		"imageURL": "video-poker-halloween-landscape.jpg",
		"linkURL": "https://www.247videopoker.org/halloween/",
		"seasonal": true
	},
	{
		"gameType": "video-poker",
		"theme": "thanksgiving",
		"imageURL": "video-poker-thanksgiving-landscape.jpg",
		"linkURL": "https://www.247videopoker.org/thanksgiving/",
		"seasonal": true
	},
	{
		"gameType": "video-poker",
		"theme": "christmas",
		"imageURL": "video-poker-christmas-landscape.jpg",
		"linkURL": "https://www.247videopoker.org/christmas/",
		"seasonal": true
	},
	{
		"gameType": "video-poker",
		"theme": "new-years",
		"imageURL": "video-poker-new-years-landscape.jpg",
		"linkURL": "https://www.247videopoker.org/new-years/",
		"seasonal": true
	},
	{
		"gameType": "poker",
		"theme": "247",
		"imageURL": "poker-247-landscape.jpg",
		"linkURL": "https://www.247freepoker.com/",
		"seasonal": true
	},
	{
		"gameType": "poker",
		"theme": "winter",
		"imageURL": "poker-winter-landscape.jpg",
		"linkURL": "https://www.247freepoker.com/winter/",
		"seasonal": true
	},
	{
		"gameType": "poker",
		"theme": "valentines",
		"imageURL": "poker-valentines-landscape.jpg",
		"linkURL": "https://www.247freepoker.com/valentines/",
		"seasonal": true
	},
	{
		"gameType": "poker",
		"theme": "st-patricks",
		"imageURL": "poker-st-patricks-landscape.jpg",
		"linkURL": "https://www.247freepoker.com/st-patricks/",
		"seasonal": true
	},
	{
		"gameType": "poker",
		"theme": "easter",
		"imageURL": "poker-easter-landscape.jpg",
		"linkURL": "https://www.247freepoker.com/easter/",
		"seasonal": true
	},
	{
		"gameType": "poker",
		"theme": "cinco-de-mayo",
		"imageURL": "poker-cinco-de-mayo-landscape.jpg",
		"linkURL": "https://www.247freepoker.com/cinco-de-mayo/",
		"seasonal": true
	},
	{
		"gameType": "poker",
		"theme": "spring",
		"imageURL": "poker-spring-landscape.jpg",
		"linkURL": "https://www.247freepoker.com/spring/",
		"seasonal": true
	},
	{
		"gameType": "poker",
		"theme": "4th-of-july",
		"imageURL": "poker-4th-of-july-landscape.jpg",
		"linkURL": "https://www.247freepoker.com/4th-of-july/",
		"seasonal": true
	},
	{
		"gameType": "poker",
		"theme": "summer",
		"imageURL": "poker-summer-landscape.jpg",
		"linkURL": "https://www.247freepoker.com/summer/",
		"seasonal": true
	},
	{
		"gameType": "poker",
		"theme": "fall",
		"imageURL": "poker-fall-landscape.jpg",
		"linkURL": "https://www.247freepoker.com/fall/",
		"seasonal": true
	},
	{
		"gameType": "poker",
		"theme": "halloween",
		"imageURL": "poker-halloween-landscape.jpg",
		"linkURL": "https://www.247freepoker.com/halloween/",
		"seasonal": true
	},
	{
		"gameType": "poker",
		"theme": "thanksgiving",
		"imageURL": "poker-thanksgiving-landscape.jpg",
		"linkURL": "https://www.247freepoker.com/thanksgiving/",
		"seasonal": true
	},
	{
		"gameType": "poker",
		"theme": "christmas",
		"imageURL": "poker-christmas-landscape.jpg",
		"linkURL": "https://www.247freepoker.com/christmas/",
		"seasonal": true
	},
	{
		"gameType": "poker",
		"theme": "new-years",
		"imageURL": "poker-new-years-landscape.jpg",
		"linkURL": "https://www.247freepoker.com/new-years/",
		"seasonal": true
	},
	{
		"gameType": "crossword",
		"theme": "247",
		"imageURL": "crossword-247-landscape.jpg",
		"linkURL": "https://www.247crossword.com/",
		"seasonal": true
	},
	{
		"gameType": "crossword",
		"theme": "winter",
		"imageURL": "crossword-winter-landscape.jpg",
		"linkURL": "https://www.247crossword.com/winter/",
		"seasonal": true
	},
	{
		"gameType": "crossword",
		"theme": "valentines",
		"imageURL": "crossword-valentines-landscape.jpg",
		"linkURL": "https://www.247crossword.com/valentines/",
		"seasonal": true
	},
	{
		"gameType": "crossword",
		"theme": "st-patricks",
		"imageURL": "crossword-st-patricks-landscape.jpg",
		"linkURL": "https://www.247crossword.com/st-patricks/",
		"seasonal": true
	},
	{
		"gameType": "crossword",
		"theme": "easter",
		"imageURL": "crossword-easter-landscape.jpg",
		"linkURL": "https://www.247crossword.com/easter/",
		"seasonal": true
	},
	{
		"gameType": "crossword",
		"theme": "cinco-de-mayo",
		"imageURL": "crossword-cinco-de-mayo-landscape.jpg",
		"linkURL": "https://www.247crossword.com/cinco-de-mayo/",
		"seasonal": true
	},
	{
		"gameType": "crossword",
		"theme": "spring",
		"imageURL": "crossword-spring-landscape.jpg",
		"linkURL": "https://www.247crossword.com/spring/",
		"seasonal": true
	},
	{
		"gameType": "crossword",
		"theme": "4th-of-july",
		"imageURL": "crossword-4th-of-july-landscape.jpg",
		"linkURL": "https://www.247crossword.com/4th-of-july/",
		"seasonal": true
	},
	{
		"gameType": "crossword",
		"theme": "summer",
		"imageURL": "crossword-summer-landscape.jpg",
		"linkURL": "https://www.247crossword.com/summer/",
		"seasonal": true
	},
	{
		"gameType": "crossword",
		"theme": "fall",
		"imageURL": "crossword-fall-landscape.jpg",
		"linkURL": "https://www.247crossword.com/fall/",
		"seasonal": true
	},
	{
		"gameType": "crossword",
		"theme": "halloween",
		"imageURL": "crossword-halloween-landscape.jpg",
		"linkURL": "https://www.247crossword.com/halloween/",
		"seasonal": true
	},
	{
		"gameType": "crossword",
		"theme": "thanksgiving",
		"imageURL": "crossword-thanksgiving-landscape.jpg",
		"linkURL": "https://www.247crossword.com/thanksgiving/",
		"seasonal": true
	},
	{
		"gameType": "crossword",
		"theme": "christmas",
		"imageURL": "crossword-christmas-landscape.jpg",
		"linkURL": "https://www.247crossword.com/christmas/",
		"seasonal": true
	},
	{
		"gameType": "crossword",
		"theme": "new-years",
		"imageURL": "crossword-new-years-landscape.jpg",
		"linkURL": "https://www.247crossword.com/new-years/",
		"seasonal": true
	},
	{
		"gameType": "pool",
		"theme": "247",
		"imageURL": "pool-247-landscape.jpg",
		"linkURL": "https://www.247pool.com/",
		"seasonal": true
	},
	{
		"gameType": "pool",
		"theme": "winter",
		"imageURL": "pool-winter-landscape.jpg",
		"linkURL": "https://www.247pool.com/winter/",
		"seasonal": true
	},
	{
		"gameType": "pool",
		"theme": "valentines",
		"imageURL": "pool-valentines-landscape.jpg",
		"linkURL": "https://www.247pool.com/valentines/",
		"seasonal": true
	},
	{
		"gameType": "pool",
		"theme": "st-patricks",
		"imageURL": "pool-st-patricks-landscape.jpg",
		"linkURL": "https://www.247pool.com/st-patricks/",
		"seasonal": true
	},
	{
		"gameType": "pool",
		"theme": "easter",
		"imageURL": "pool-easter-landscape.jpg",
		"linkURL": "https://www.247pool.com/easter/",
		"seasonal": true
	},
	{
		"gameType": "pool",
		"theme": "cinco-de-mayo",
		"imageURL": "pool-cinco-de-mayo-landscape.jpg",
		"linkURL": "https://www.247pool.com/cinco-de-mayo/",
		"seasonal": true
	},
	{
		"gameType": "pool",
		"theme": "spring",
		"imageURL": "pool-spring-landscape.jpg",
		"linkURL": "https://www.247pool.com/spring/",
		"seasonal": true
	},
	{
		"gameType": "pool",
		"theme": "4th-of-july",
		"imageURL": "pool-4th-of-july-landscape.jpg",
		"linkURL": "https://www.247pool.com/4th-of-july/",
		"seasonal": true
	},
	{
		"gameType": "pool",
		"theme": "summer",
		"imageURL": "pool-summer-landscape.jpg",
		"linkURL": "https://www.247pool.com/summer/",
		"seasonal": true
	},
	{
		"gameType": "pool",
		"theme": "fall",
		"imageURL": "pool-fall-landscape.jpg",
		"linkURL": "https://www.247pool.com/fall/",
		"seasonal": true
	},
	{
		"gameType": "pool",
		"theme": "halloween",
		"imageURL": "pool-halloween-landscape.jpg",
		"linkURL": "https://www.247pool.com/halloween/",
		"seasonal": true
	},
	{
		"gameType": "pool",
		"theme": "thanksgiving",
		"imageURL": "pool-thanksgiving-landscape.jpg",
		"linkURL": "https://www.247pool.com/thanksgiving/",
		"seasonal": true
	},
	{
		"gameType": "pool",
		"theme": "christmas",
		"imageURL": "pool-christmas-landscape.jpg",
		"linkURL": "https://www.247pool.com/christmas/",
		"seasonal": true
	},
	{
		"gameType": "pool",
		"theme": "new-years",
		"imageURL": "pool-new-years-landscape.jpg",
		"linkURL": "https://www.247pool.com/new-years/",
		"seasonal": true
	},
	{
		"gameType": "wordley",
		"theme": "247",
		"imageURL": "wordley-247-landscape.jpg",
		"linkURL": "https://247wordley.com/"
	},
	{
		"gameType": "pinball",
		"theme": "247",
		"imageURL": "pinball-247-landscape.jpg",
		"linkURL": "https://www.247pinball.com/"
	},
	{
		"gameType": "mahjong",
		"theme": "247",
		"imageURL": "mahjong-247-landscape.jpg",
		"linkURL": "https://www.247mahjong.com/"
	},
	{
		"gameType": "sudoku",
		"theme": "247",
		"imageURL": "sudoku-247-landscape.jpg",
		"linkURL": "https://www.247sudoku.com/"
	},
	{
		"gameType": "checkers",
		"theme": "247",
		"imageURL": "checkers-247-landscape.jpg",
		"linkURL": "https://www.247checkers.com/"
	},
	{
		"gameType": "chess",
		"theme": "247",
		"imageURL": "chess-247-landscape.jpg",
		"linkURL": "https://www.247chess.com/"
	},
	{
		"gameType": "space-rocks",
		"theme": "247",
		"imageURL": "space-rocks-247-landscape.jpg",
		"linkURL": "https://www.247spacerocks.com/"
	},
	{
		"gameType": "[none]",
		"theme": "[none]",
		"imageURL": "247-newsletter-landscape.jpg",
		"linkURL": "https://247games.com/newsletter/"
	}
];

	// Edit the game link entries to prepend the promos image directory and append the link url args
	for (var i = 0; i < gameLinks.length; ++i)
	{
		gameLinks[i].imageURL = "https://www.247games.com/feature-lineup/promos/" + gameLinks[i].imageURL;
		gameLinks[i].linkURL = gameLinks[i].linkURL + "?promo=1";
	}

	/** @type {FeatureLineupCalendarEntry[]} Entries must be sorted, the build process should handle this. */
	var calendar = [
	{
		"theme": "winter",
		"month": 1,
		"day": 2
	},
	{
		"theme": "valentines",
		"month": 2,
		"day": 2
	},
	{
		"theme": "st-patricks",
		"month": 2,
		"day": 17
	},
	{
		"theme": "easter",
		"month": 3,
		"day": 18
	},
	{
		"theme": "spring",
		"month": 4,
		"day": 1
	},
	{
		"theme": "summer",
		"month": 5,
		"day": 15
	},
	{
		"theme": "4th-of-july",
		"month": 6,
		"day": 27
	},
	{
		"theme": "summer",
		"month": 7,
		"day": 5
	},
	{
		"theme": "247",
		"month": 8,
		"day": 5
	},
	{
		"theme": "fall",
		"month": 9,
		"day": 5
	},
	{
		"theme": "halloween",
		"month": 10,
		"day": 1
	},
	{
		"theme": "thanksgiving",
		"month": 11,
		"day": 4
	},
	{
		"theme": "christmas",
		"month": 12,
		"day": 1
	},
	{
		"theme": "new-years",
		"month": 12,
		"day": 26
	}
];

	// Find current month and day of the month to help choose standard lineup contents, allow args overrides;
	var now = new Date();
	var month = now.getMonth() + 1;	// 0 indexed
	var day = now.getDate();
	if (args.overrideMonth) month = args.overrideMonth;
	if (args.overrideDay) day = args.overrideDay;

	// Determine the current seasonal theme using the month, day, and calendar
	var currentCalendarTheme = calendar[calendar.length - 1];
	for (var i = 0; i < calendar.length; ++i)
	{
		if (calendar[i].month > month)
		{
			break;
		}
		else if (calendar[i].month === month)
		{
			if (calendar[i].day > day)
			{
				break;
			}
		}
		currentCalendarTheme = calendar[i];
	}

	// Cull the game links that are out of season
	for (var i = 0; i < gameLinks.length; ++i)
	{
		if (gameLinks[i].seasonal && gameLinks[i].theme !== currentCalendarTheme.theme)
		{
			if (gameLinks.length !== 1)
			{
				gameLinks.splice(i, 1);
				i--;
			}
		}
	}

	// Identify the current game type and seasonal variation, if its in the list
	var currentGameTypeAndSeasonEntry = null;
	for (var i = 0; i < gameLinks.length; ++i)
	{
		if (gameLinks[i].gameType === args.gameType && gameLinks[i].theme === currentCalendarTheme.theme)
		{
			//console.log("identified currentGameTypeAndSeasonEntry");
			currentGameTypeAndSeasonEntry = gameLinks[i];
			break;
		}
	}
	//console.log("currentGameTypeAndSeasonEntry", currentGameTypeAndSeasonEntry);
	for (var i = 0; i < gameLinks.length; ++i)
	{
		if (gameLinks[i].currentGameCurrentSeason)
		{
			if (currentGameTypeAndSeasonEntry)
			{
				//console.log("found match", i);
				gameLinks[i].gameType = currentGameTypeAndSeasonEntry.gameType;
				gameLinks[i].imageURL = currentGameTypeAndSeasonEntry.imageURL;
				gameLinks[i].linkURL = currentGameTypeAndSeasonEntry.linkURL;
				gameLinks[i].theme = currentGameTypeAndSeasonEntry.theme;
			}
			else
			{
				//console.log("found currentGameCurrentSeason entry, but did not have a match", i);
				gameLinks.splice(i, 1);
				i--;
			}
		}
	}

	// Cull the game link entries that are the same gameType and theme as the currently displayed page
	for (var i = 0; i < gameLinks.length; ++i)
	{
		if (gameLinks[i].theme === args.theme && gameLinks[i].gameType === args.gameType)
		{
			if (gameLinks.length !== 1)
			{
				gameLinks.splice(i, 1);
				i--;
			}
		}
	}

	// Remove duplicates
	// IE: we could specify 247 minesweeper AND the current theme could be 247, so 247 minesweeper could be in the lineup twice
	// remove the second entry
	let dupeKeyTable = {};
	for (var i = 0; i < gameLinks.length; ++i)
	{
		let key = gameLinks[i].gameType + "::" + gameLinks[i].theme;
		if (dupeKeyTable[key])
		{
			gameLinks.splice(i, 1);
			i--;
		}
		else
		{
			dupeKeyTable[key] = true;
		}
	}

	return gameLinks;
};


